### ISSUE TITLE
Squremarker doesn't work on 1.19.3

### ISSUE THREAD

**Issue by Alarize** [SentixDev/squaremarker#14] opened 2023-03-05 10:27 UTC
Have a proble with this plugin. It doesn't work at all, even though, it's crashing other pugins! Here is the Error:
https://pastes.dev/XJGC8c11hp
P.S: This is the LATEST version

**Comment by jpenilla** [comment] 2023-03-05 19:35
If this is caused by your use of `/reload` then this is a wontfix, please share a full log where the issue occurs without `/reload` having been used.

**Comment by Alarize** [comment] 2023-03-05 20:23
It caused even with restart

**Comment by Alarize** [comment] 2023-03-05 20:27
> If this is caused by your use of `/reload` then this is a wontfix, please share a full log where the issue occurs without `/reload` having been used.
Here is the log with /restart action: https://pastes.dev/HcTgdvECrc

**Comment by jpenilla** [comment] 2023-03-06 16:25
Try changing the icon url in the config to `https://raw.githubusercontent.com/SentixDev/squaremarker/master/resources/default_icon.png`

**Closed** 2023-09-09 04:36 UTC
